<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>Formulario de inicio de sesión - MOP</title>';
echo '<style>';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'background-color: #f5f5f5;';
echo '}';
echo '';
echo 'h2 {';
echo 'color: #003366;';
echo '}';
echo '';
echo 'form {';
echo 'width: 300px;';
echo 'margin: 0 auto;';
echo 'background-color: #ffffff;';
echo 'padding: 20px;';
echo 'border: 1px solid #cccccc;';
echo 'border-radius: 5px;';
echo 'box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);';
echo '}';
echo '';
echo 'label {';
echo 'display: block;';
echo 'margin-bottom: 10px;';
echo 'color: #003366;';
echo '}';
echo '';
echo 'input[type="text"],';
echo 'input[type="password"] {';
echo 'width: 100%;';
echo 'padding: 8px;';
echo 'border: 1px solid #cccccc;';
echo 'border-radius: 4px;';
echo '}';
echo '';
echo 'input[type="submit"] {';
echo 'width: 100%;';
echo 'padding: 8px;';
echo 'background-color: #003366;';
echo 'color: #ffffff;';
echo 'border: none;';
echo 'border-radius: 4px;';
echo 'cursor: pointer;';
echo '}';
echo '';
echo 'input[type="submit"]:hover {';
echo 'background-color: #002255;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<h2>Inicio de sesión - MOP</h2>';
echo '<form action="login.php" method="post">';
echo '<div>';
echo '<label for="username">Nombre de usuario:</label>';
echo '<input type="text" id="username" name="username" required>';
echo '</div>';
echo '<div>';
echo '<label for="password">Contraseña:</label>';
echo '<input type="password" id="password" name="password" required>';
echo '</div>';
echo '<div>';
echo '<input type="submit" value="Iniciar sesión">';
echo '</div>';
echo '</form>';
echo '</body>';
echo '</html>';
echo '';
?>